### ISSUE TITLE
Remove "class", "DITAArchVersion" and "domains" attributes when generating DITA content

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#13]
They make the generated DITA content look ugly.

**Comment by DunaMariusCosmin** [comment]
Fixed in: 6a645487155f03d144d75b7cc13b4537bb461147

**Comment by raducoravu** [comment]
As code review, I would maybe have created an implementation of ContentPrinter called maybe something like "DITAFilterAttributesPrinter" which would have applied that filter XSLT.
And then chain this new filter printer with the other printers which create the DITA content from MD, HTML or XHTML.
