### ISSUE TITLE
Conversion plugin somehow influences the Oxygen Markdown editor

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#14]
Once I install the plugin and use it, if I open a markdown file in Oxygen the "Preview" part on the right side shows a class cast error.

**Comment by raducoravu** [comment]
If the plugin changes system properties, does it change them back when finished?

**Comment by sorincarbunaru** [comment]
The class cast error does not to seem to be related to the plugin. I have a "pluginless" oXygen, I reset the global options, and the problem still happens. Probably this issue should be closed...
