### ISSUE TITLE
Problem converting email from markdown to xhtml

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#25]
In this sample markdown there is an email address:

            # Title
            
            Text
              
             ![A beautiful flower](../dita/flowers/images/Chrysanthemums.jpg "Chrysanthemum")
             
             
             http://www.google.fr/
            
            Email:
            
            <address@example.com>
            
            
            line1
            continues here
            
            line2 has more
            content

which does not get properly converted to XHTML using the plugin. In Oxygen the Markdown HTML preview properly converts the email address to an HTML link.

**Comment by DunaMariusCosmin** [comment]
This will work properly if the blank line after "Email:" will be deleted.
