### ISSUE TITLE
Convert XML to JSON

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#7]
Add action to convert from XML to JSON. Mount action to Tools Menu and to Project contextuale menu (in a special "Batch Convert" submenu). One possibility to make this work is to use the method "org.json.XML.toJSONObject(String)" from the "json.jar" which comes bundled with Oxygen. 
Another way would be to try and use some other library.

**Comment by DunaMariusCosmin** [comment]
Fixed in: 7e1ea2c55dba09e0aa4fd6ffa043dad4820df198
