### ISSUE TITLE
Convert JSON to XML

### ISSUE THREAD

**Issue by raducoravu** [oxygenxml/oxygen-resources-convertor#8]
Add action to convert from JSON to XML. Mount action to Tools Menu and to Project contextuale menu (in a special "Batch Convert" submenu.
In our internal code for the simple action which converts a single JSON to XML we use the "json.jar" bundled with Oxygen and we use some code like:

          private static StringBuilder convertToXML(Reader reader, boolean addJSONTag) throws IOException {
            // Switch the reader to an XML content
            try {
              String jsonContent = IOUtil.read(reader).toString();
              JSONType jsonType = getType(jsonContent);
              if (jsonType == null) {
                throw new JSONException(INVALID_JSON_CONTENT_MESSAGE);
              } 
              if (jsonType == JSONType.ARRAY_TYPE) {
                // We have a top level array. Wrap into an object
                jsonContent = "{\"JSON_ARRAY\":" + jsonContent + "}";
              }
              JSONObject jsonObject = new JSONObject(jsonContent);
              StringBuilder jsonContentBuilder = new StringBuilder();
              // Surround with artificial tag, always make it well-formed
              if(addJSONTag || jsonObject.length() != 1){
                jsonContentBuilder.append("<JSON>");
              }
              jsonContentBuilder.append(XML.toString(jsonObject));
              if(addJSONTag || jsonObject.length() != 1){
                jsonContentBuilder.append("</JSON>");
              }
              return jsonContentBuilder;
            } catch (JSONException e) {
              throw new IOException(e.getMessage());
            }
          }

or you can try to find a third party library for this.

**Comment by DunaMariusCosmin** [comment]
Fixed in: 7e1ea2c55dba09e0aa4fd6ffa043dad4820df198
